### ISSUE TITLE
Bug: Two open ports rewrites first port

### ISSUE THREAD

**Issue by epanas** [claudioarena/mdt69x#1]
Hello!

Below, I noticed there seems to be a bug in the code where once you open a second port the first port is rewritten. As we can see the controller_left has a seriel number of 170508175407 and controller_right has a serial number is 170201175407 but once the second controller is configured if we rerun the id function we can see the controller is now assigned to170201175407 for the left and right controller.

Thank you.

![mdt69x_bug](https://user-images.githubusercontent.com/51330764/174150351-c185e4a6-15cd-44e3-9622-201355cd1aca.PNG)

**Comment by claudioarena** [comment]
That is weird...and I am not entirely sure I can help.
I do not have physical access to the controller anymore.

You could try investigating what is going on, and I'd be happy to update the code if we figure it out.

If you have a look at the code:
-get_id() sends a command to the serial port, and prints the response. So it must be sending the command to the wrong port (always to the last open port?). You can check this by debugging the code, or adding a print(self._ser.port) in the get_id() call.
-the serial port object (_ser) is set once the class object is initiated, and shouldn't be changed by making another class object. This is clearly happening...so either there is some weirdness in the serial class or in my use of it.

The other thing you can try as a sanity check. Add a variable to the class, similar to the _ser variable. Call it "id" or "name" or something similar. Use this as a simple text variable, which you can set on initiation (just like for the serial class), and you can print its value when you call the get_id() class. This way you can check that a text value variable stays with the class, and there isn't any weird global variable setting causing issues.

If the above works it sort of implies that the serial object is also staying with the class instance as expected, and I would worry that there is some issue in the use of the serial class. I tend to be overly cautious and close and open the port more that it might be needed, to avoid a hanged open port. Maybe that is causing issues?
You can try if re-initiazing the controller you need each time works? I realise it's a horrible solution, but it could point to what the issue is?

**Comment by claudioarena** [comment]
I am sorry I can not help you more, but it is hard without the hardware in front of me. I could hack some hardware simulator over the weekend to figure something out, but I am not sure I will have the time.

Another few things about your example code:
-print(controller_left) doesn't do anything I believe.
-get_id() directly calls a print function. No need to encapsulate it around print(). If fact, that causes you to get a "None"
-COM256 is the highest window port number available. Can you change the com port numbers to lower numbers? I doubt that is the problem, but you never know...

**Comment by claudioarena** [comment]
Update on this: I've put together a quick hardware emulator of the device, and was able to reproduce the error. I will see if I can fix the bug in the next few days

**Comment by claudioarena** [comment]
Please try now, after updating the package using pip.

It was a fairly simple mistake on my part - some of the variables that needed to be instance variables were class variable instead.
No surprise then that they were being changed by different instances of the class :)

Let me know if it all works now if you can

**Comment by epanas** [comment]
Good morning !

So sorry for the delay this is fantastic. I was able to easily update and get my code working. Thank you so much for your helpful and timely responses. :)

**Comment by claudioarena** [comment]
no worries, glad it worked!
